# Generated by Django 6.0.3 on 2026-03-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Co_Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkerID', models.CharField(max_length=25)),
                ('Name', models.CharField(max_length=25)),
                ('Designation', models.CharField(max_length=25)),
                ('Age', models.PositiveSmallIntegerField()),
                ('Address', models.CharField(max_length=255)),
                ('HomeDistrict', models.CharField(max_length=25)),
                ('NID', models.CharField(max_length=25)),
                ('JoinDate', models.DateField()),
                ('YearOfExperience', models.PositiveSmallIntegerField()),
                ('PreviouslyWorkedIn', models.TextField()),
                ('WorkingHours', models.CharField(max_length=25)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseID', models.CharField(max_length=25)),
                ('Name', models.CharField(max_length=25)),
                ('Duration', models.CharField(max_length=25)),
                ('Description', models.TextField()),
                ('Syllabus', models.TextField()),
                ('TrainerAssigned', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.CharField(max_length=25)),
                ('Name', models.CharField(max_length=25)),
                ('CourseEnrolled', models.CharField(max_length=25)),
                ('Batch', models.CharField(max_length=25)),
                ('Age', models.PositiveSmallIntegerField()),
                ('Address', models.CharField(max_length=255)),
                ('HomeDistrict', models.CharField(max_length=25)),
                ('NID', models.CharField(max_length=25)),
                ('ProgressStatus', models.CharField(max_length=25)),
                ('PreviousSkills', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrainerID', models.CharField(max_length=25)),
                ('Name', models.CharField(max_length=25)),
                ('Designation', models.CharField(max_length=25)),
                ('Age', models.PositiveSmallIntegerField()),
                ('Address', models.CharField(max_length=25)),
                ('HomeDistrict', models.CharField(max_length=25)),
                ('NID', models.CharField(max_length=25)),
                ('JoinDate', models.DateField()),
                ('YearOfExperience', models.PositiveSmallIntegerField()),
                ('PreviouslyWorkedIn', models.TextField()),
                ('WorkingHours', models.CharField(max_length=25)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CourseAssigned', models.CharField(max_length=25)),
                ('BatchAssigned', models.CharField(max_length=25)),
            ],
        ),
    ]
