# Generated by Django 6.0.3 on 2026-03-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Name',
            field=models.CharField(max_length=200),
        ),
    ]
