# Generated by Django 6.0.3 on 2026-03-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_app', '0002_alter_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='CourseAssigned',
            field=models.CharField(max_length=200),
        ),
    ]
